{
 "title": "dash-app-loja-api",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"},pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Infra Api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heap Used",
   "type": "gauge",
   "description": "Memoria heap utilizada",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\",area=\"heap\"}) * 100 / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\",area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nonheap used",
   "type": "gauge",
   "description": "Memoria non-heap utilizada",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\",area=\"nonheap\"}) * 100 / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\",area=\"nonheap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Utilização de CPU",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\"}",
     "legendFormat": "Sys CPU usage"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\"}",
     "legendFormat": "Process CPU usage"
    }
   ]
  },
  {
   "title": "Api Red",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error 500",
     "type": "stat",
     "description": "Quantidade de error 500 ultimo min.",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", uri != \"/actuator/prometheus\", status=\"500\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total request",
     "type": "stat",
     "description": "Número total de requests no ultimo min",
     "gridPos": { "h": 5, "w": 4, "x": 3, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", uri != \"/actuator/prometheus\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avarege duration request",
     "type": "timeseries",
     "description": "Duração media de request no ultimo min",
     "gridPos": { "h": 5, "w": 10, "x": 7, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", status=\"200\", uri=\"/topicos\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", status=\"200\", uri=\"/topicos\"}[1m])",
       "legendFormat": "{{uri}} {{method}} {{status}"
      },
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", status=\"200\", uri=\"/topicos/{id}\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", status=\"200\", uri=\"/topicos/{id}\"}[1m])",
       "legendFormat": "{{uri}} {{method}} {{status}"
      },
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", status=\"200\", uri=\"/auth\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", status=\"200\", uri=\"/auth\"}[1m])",
       "legendFormat": "{{uri}} {{method}} {{status}"
      }
     ]
    },
    {
     "title": "Error rate",
     "type": "timeseries",
     "description": "Taxa de error nos últimos 5 min",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", uri != \"/actuator/prometheus\", status=\"500\" }[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", uri != \"/actuator/prometheus\"}[5m]))",
       "legendFormat": "500"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", uri != \"/actuator/prometheus\", status=\"400\" }[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", uri != \"/actuator/prometheus\"}[5m]))",
       "legendFormat": "400"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", uri != \"/actuator/prometheus\", status=\"404\" }[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", uri != \"/actuator/prometheus\"}[5m]))",
       "legendFormat": "404"
      }
     ]
    },
    {
     "title": "Max. Request Duration",
     "type": "timeseries",
     "description": "Duração máxima de uma request",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", status=\"200\", uri != \"/actuator/prometheus\"}",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      }
     ]
    },
    {
     "title": "Request count",
     "type": "timeseries",
     "description": "Número de requests por endepoint no ultimo min",
     "gridPos": { "h": 6, "w": 13, "x": 10, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", uri=\"/topicos\"}[1m]))",
       "legendFormat": "/topicos"
      },
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", uri=\"/topicos/{id}\"}[1m]))",
       "legendFormat": "/topicos/{id]"
      },
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", uri=\"/auth\"}[1m]))",
       "legendFormat": "/auth"
      }
     ]
    },
    {
     "title": "Response time",
     "type": "timeseries",
     "description": "Tempo de resposta no ultimo min",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", uri != \"/actuator/prometheus\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", uri != \"/actuator/prometheus\"}[1m])",
       "legendFormat": "{{uri}}, {{method}}, {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Api Basic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Start Time",
     "type": "stat",
     "description": "Start API ",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\"} * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "User Logon",
     "type": "stat",
     "description": "Usuários logados com sucesso",
     "gridPos": { "h": 4, "w": 4, "x": 5, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(auth_user_success_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JDBC Pool",
     "type": "stat",
     "description": "Pool de conexões JDBC",
     "gridPos": { "h": 4, "w": 4, "x": 9, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", pool=\"$pool\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connection state",
     "type": "timeseries",
     "description": "Estado de conexão com database",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", pool=\"$pool\"}",
       "legendFormat": "active"
      },
      {
       "expr": "hikaricp_connections_idle{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", pool=\"$pool\"}",
       "legendFormat": "idle"
      },
      {
       "expr": "hikaricp_connections_pending{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", pool=\"$pool\"}",
       "legendFormat": "pending"
      }
     ]
    },
    {
     "title": "UpTime",
     "type": "stat",
     "description": "api upTime",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Auth Errors",
     "type": "stat",
     "description": "Errors auth",
     "gridPos": { "h": 4, "w": 4, "x": 5, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(auth_user_error_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database TimeOut",
     "type": "stat",
     "description": "conexões com database em timeout",
     "gridPos": { "h": 4, "w": 4, "x": 9, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(hikaricp_connections_timeout_total{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", pool=\"$pool\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Warn & Error log",
     "type": "timeseries",
     "description": "warnings e errors últimos 5 min",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", level=\"warn\"}[5m]))",
       "legendFormat": "Warn"
      },
      {
       "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-loja-mkt\", level=\"error\"}[5m]))",
       "legendFormat": "Error"
      }
     ]
    }
   ]
  }
 ]
}