version: '3.8'

services:
  srv-prometheus:
    image: prom/prometheus
    container_name: srv-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  srv-grafana:
    image: grafana/grafana
    container_name: srv-grafana
    volumes:
      - ./grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - srv-prometheus

networks:
  monitoring:
