global:
  scrape_interval: 5s
scrape_configs:
- job_name: prometheus-forum-api
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ['host.docker.internal:9090']
- job_name: app-loja-mkt
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['host.docker.internal:8090']  # Ou substitua por seu IP local se estiver usando Linux